FROM --platform=${TARGETPLATFORM} restic/restic:0.18.0@sha256:4cf4a61ef9786f4de53e9de8c8f5c040f33830eb0a10bf3d614410ee2fcb6120

# hadolint ignore=DL3018
RUN apk add --update --no-cache mariadb-client mariadb-connector-c
