FROM --platform=${TARGETPLATFORM} restic/restic:0.18.1@sha256:39d9072fb5651c80d75c7a811612eb60b4c06b32ffe87c2e9f3c7222e1797e76

# hadolint ignore=DL3018
RUN apk add --update --no-cache mariadb-client mariadb-connector-c
